//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePageForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public byte[] picture { get; set; }
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public Nullable<int> date_birth { get; set; }
        public string marital { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<int> Phone_no { get; set; }
        public Nullable<int> zip_code { get; set; }
    }
}
