//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePageForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_id { get; set; }
        public string Emp_name { get; set; }
        public Nullable<int> Date_of_birth { get; set; }
        public Nullable<int> Date_of_joint { get; set; }
        public Nullable<int> Application_date { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string State { get; set; }
        public string Designation { get; set; }
        public Nullable<int> E_code { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> phone_no { get; set; }
    }
}
