//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePageForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public string lname { get; set; }
        public Nullable<int> l_no { get; set; }
        public string l_type { get; set; }
        public string address { get; set; }
        public Nullable<int> Application_date { get; set; }
        public string Email_address { get; set; }
        public string grantee_provided { get; set; }
        public Nullable<int> Annual_income { get; set; }
        public Nullable<int> Amount_Loan { get; set; }
        public int l_code { get; set; }
    }
}
